#author: Andreas Karageorgos
#github: https://github.com/AndreasKarageorgos
#plugin: https://github.com/AndreasKarageorgos/Herobrine
###########################################################
###########################################################
#By increasing the 'scare' players get lesser chance of getting scared. (Minimum is 1)
scare: 5
disable-scare: false
#By increasing the 'jumpscare' players get lesser chance of getting JumpScare. (Minumum is 1)
jumpscare: 5
spawn-mobs: true
disable-jumpscare: false
#
#
#The plugin randomly chooses the time bitween the min and max time for the next scare.
min: 60
max: 160
############################################################################################
console-warnings: true
#if 'scare-everyone' is enabled then the players will not be required to use the /herobrine command.
scare-everyone: false
