main: net.assassincraft.play.Main
name: Herobrine
version: 0.2
author: Andreas_Karageorgos
website: https://127.0.0.1/
description: This plugin is made to make servers scary for tough people !
api-version: 1.16

commands:
   herobrine:
