main: net.assassincraft.play.Main
name: Herobrine
version: 4.0
author: AndreasKarageorgos
website: https://github.com/AndreasKarageorgos/Herobrine
description: This plugin will start plays sounds randomly to scare players and spawn Herobrine.
api-version: 1.16


commands:
   herobrine:
